### ISSUE TITLE
Force close on button click

### ISSUE THREAD

**Issue by viktapas** [vikaskumar-vsk/STT#1]
catlog:
```
03-26 19:54:02.048 17930-17930/labs.ika.speechtotext E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: labs.ika.speechtotext, PID: 17930
                                                                       java.lang.RuntimeException: labs.ika.speechtotext.MainActivity@1fe1e58 must implement OnFragmentInteractionListener
                                                                           at labs.ika.speechtotext.AsyncFragment.onAttach(AsyncFragment.java:83)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1231)
                                                                           at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
                                                                           at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
                                                                           at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6169)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

```

**Comment by imflash217** [comment]
http://stackoverflow.com/questions/24777985/how-to-implement-onfragmentinteractionlistener

http://stackoverflow.com/questions/28822229/error-must-implement-onfragmentinteractionlistener

**Comment by imflash217** [comment]
any updates??

**Comment by viktapas** [comment]
Not understanding what to do...😞

**Comment by imflash217** [comment]
AsyncFragment.java @  lineNo. 94 : 
```java

/**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
```
MainActivity.java : 
Make following changes : 
```java
public class MainActivity extends AppCompatActivity implements AsyncFragment.OnFragmentInteractionListener {
......
@Override
    public void onFragmentInteraction(Uri uri){
    }
....
}
```
This will solve the issue of crash of BottomNavigation button click....

**Comment by imflash217** [comment]
refer this link for more insights:
http://stackoverflow.com/questions/28822229/error-must-implement-onfragmentinteractionlistener
